### ISSUE TITLE
mintMenuConfig.py doen't run and aborts with gtk errors

### ISSUE THREAD

**Issue by raveit65** [linuxmint/mintmenu#148]
origin downstream report: fedora 23
https://bugzilla.redhat.com/show_bug.cgi?id=1293105
```
 Manni Heumann 2015-12-20 05:34:06 EST

Description of problem:

clicking on "Preferences" in mintmenu's context menu does nothing.

Trying from the shell:

# /usr/share/linuxmint/mintMenu/mintMenuConfig.py
/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
Traceback (most recent call last):
  File "/usr/share/linuxmint/mintMenu/mintMenuConfig.py", line 536, in <module>
    window = mintMenuConfig()
  File "/usr/share/linuxmint/mintMenu/mintMenuConfig.py", line 293, in __init__
    self.getBackgroundColor()
  File "/usr/share/linuxmint/mintMenu/mintMenuConfig.py", line 380, in getBackgroundColor
    self.backgroundColor.get_color(color)
TypeError: Gtk.ColorButton.get_color() takes exactly 1 argument (2 given)


Version-Release number of selected component (if applicable):
5.6.5

How reproducible:
always

Steps to Reproduce:
see Description above

Actual results:
mintmenu configuration impossible

Expected results:
mintmenu configuration possible
```
```
 Manni Heumann 2015-12-23 03:49:03 EST

Checked. All those packages are installed and dnf reports "Nothing to do.".

By the way: deleting line 380 from mintMenuConfig.py makes the script run just fine.
```

**Comment by XRevan86** [comment]
This should fix it.
``` diff
--- a/usr/lib/linuxmint/mintMenu/mintMenuConfig.py
+++ b/usr/lib/linuxmint/mintMenu/mintMenuConfig.py
@@ -386,8 +386,11 @@ class mintMenuConfig( object ):
         self.headingColorLabel.set_sensitive(  widget.get_active() )
 
     def getBackgroundColor( self ):
-        color = Gdk.Color(0,0,0)
-        self.backgroundColor.get_color(color)
+        try:
+            color = self.backgroundColor.get_color()
+        except TypeError:
+            color = Gdk.Color(0, 0, 0)
+            self.backgroundColor.get_color(color)
         return self.gdkColorToString( color )
 
     def getBorderColor( self ):
```

**Comment by mannih** [comment]
Yes that patch works for me. Tjank you!

But why do I have a diffirent prototype for that function than everybody else?

**Comment by XRevan86** [comment]
@mannih Something changed in Gtk (possibly only Gtk2) introspection: newer systems are affected.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintmenu/commits/master
