### ISSUE TITLE
Issue after switch to Python 3.9

### ISSUE THREAD

**Issue by MikePooh** [linuxmint/mintmenu#260]
After updating Python to version 3.9 the start menu icon becomes invisible. I've tried to bind Mintmenu to the panel manually, it allows to launch start menu, but there is no translations inside and Error message instead applications section.

```
Traceback (most recent call last):

  File "/usr/lib/linuxmint/mintMenu/mintMenu.py", line 130, in PopulatePlugins
    X = __import__(plugin)

  File "/usr/lib/linuxmint/mintMenu/plugins/applications.py", line 15, in <module>
    gi.require_version("XApp", "1.0")

  File "/usr/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)

ValueError: Namespace XApp not available

```
python-xapp is installed, version 2.0.2-2

Arch Linux 5.9.11

**Comment by clefebvre** [comment]
Can you show me the content of python-xapp in Arch? Maybe it only provides for python 3.8?

**Comment by MikePooh** [comment]
It seems your version is correct

```
mike@mike-pc:~$ yaourt -Fl python-xapp
python-xapp usr/
python-xapp usr/lib/
python-xapp usr/lib/python3.8/
python-xapp usr/lib/python3.8/site-packages/
python-xapp usr/lib/python3.8/site-packages/python_xapp-2.0.0-py3.8.egg-info/
python-xapp usr/lib/python3.8/site-packages/python_xapp-2.0.0-py3.8.egg-info/PKG-INFO
python-xapp usr/lib/python3.8/site-packages/python_xapp-2.0.0-py3.8.egg-info/SOURCES.txt
python-xapp usr/lib/python3.8/site-packages/python_xapp-2.0.0-py3.8.egg-info/dependency_links.txt
python-xapp usr/lib/python3.8/site-packages/python_xapp-2.0.0-py3.8.egg-info/top_level.txt
python-xapp usr/lib/python3.8/site-packages/xapp/
python-xapp usr/lib/python3.8/site-packages/xapp/GSettingsWidgets.py
python-xapp usr/lib/python3.8/site-packages/xapp/SettingsWidgets.py
python-xapp usr/lib/python3.8/site-packages/xapp/__init__.py
python-xapp usr/lib/python3.8/site-packages/xapp/__pycache__/
python-xapp usr/lib/python3.8/site-packages/xapp/__pycache__/GSettingsWidgets.cpython-38.opt-1.pyc
python-xapp usr/lib/python3.8/site-packages/xapp/__pycache__/GSettingsWidgets.cpython-38.pyc
python-xapp usr/lib/python3.8/site-packages/xapp/__pycache__/SettingsWidgets.cpython-38.opt-1.pyc
python-xapp usr/lib/python3.8/site-packages/xapp/__pycache__/SettingsWidgets.cpython-38.pyc
python-xapp usr/lib/python3.8/site-packages/xapp/__pycache__/__init__.cpython-38.opt-1.pyc
python-xapp usr/lib/python3.8/site-packages/xapp/__pycache__/__init__.cpython-38.pyc
python-xapp usr/lib/python3.8/site-packages/xapp/__pycache__/os.cpython-38.opt-1.pyc
python-xapp usr/lib/python3.8/site-packages/xapp/__pycache__/os.cpython-38.pyc
python-xapp usr/lib/python3.8/site-packages/xapp/os.py
```

**Comment by clefebvre** [comment]
ah, I didn't know the package manager was called like that :)

Ok, so this should be fixed by the Arch maintainer directly. The module can be shipped for all versions of python3:

```
clem@airtop ~ $ apt content python3-xapp 
/.
/usr
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/python_xapp-2.0.2.egg-info
/usr/lib/python3/dist-packages/python_xapp-2.0.2.egg-info/dependency_links.txt
/usr/lib/python3/dist-packages/python_xapp-2.0.2.egg-info/PKG-INFO
/usr/lib/python3/dist-packages/python_xapp-2.0.2.egg-info/top_level.txt
/usr/lib/python3/dist-packages/xapp
/usr/lib/python3/dist-packages/xapp/GSettingsWidgets.py
/usr/lib/python3/dist-packages/xapp/__init__.py
/usr/lib/python3/dist-packages/xapp/os.py
/usr/lib/python3/dist-packages/xapp/SettingsWidgets.py
/usr/share
/usr/share/doc
/usr/share/doc/python3-xapp
/usr/share/doc/python3-xapp/changelog.gz
/usr/share/doc/python3-xapp/copyright
```

**Comment by eli-schwartz** [comment]
Bug report is nonsense, `pacman -Fl` does not report the contents of the installed package. It reports the ancient contents of the last time you synced `pacman -Fy` to get a remote listing, and using a completely different package version number.

I definitely rebuilt it.

https://www.archlinux.org/packages/ -> python-xapp
https://www.archlinux.org/packages/community/any/python-xapp/ -> View the file list for python-xapp
https://www.archlinux.org/packages/community/any/python-xapp/files/

Behold, python 3.9.

```
$ python
Python 3.9.0 (default, Oct  7 2020, 23:09:01) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi.repository
>>> gi.require_version("XApp", "1.0")
>>> from gi.repository import XApp
>>> 
```

**Comment by MikePooh** [comment]
You are right, my request was wrong the correct one should be

```
mike@mike-pc:~$ yaourt -Ql python-xapp
python-xapp /usr/
python-xapp /usr/lib/
python-xapp /usr/lib/python3.9/
python-xapp /usr/lib/python3.9/site-packages/
python-xapp /usr/lib/python3.9/site-packages/python_xapp-2.0.2-py3.9.egg-info/
python-xapp /usr/lib/python3.9/site-packages/python_xapp-2.0.2-py3.9.egg-info/PKG-INFO
python-xapp /usr/lib/python3.9/site-packages/python_xapp-2.0.2-py3.9.egg-info/SOURCES.txt
python-xapp /usr/lib/python3.9/site-packages/python_xapp-2.0.2-py3.9.egg-info/dependency_links.txt
python-xapp /usr/lib/python3.9/site-packages/python_xapp-2.0.2-py3.9.egg-info/top_level.txt
python-xapp /usr/lib/python3.9/site-packages/xapp/
python-xapp /usr/lib/python3.9/site-packages/xapp/GSettingsWidgets.py
python-xapp /usr/lib/python3.9/site-packages/xapp/SettingsWidgets.py
python-xapp /usr/lib/python3.9/site-packages/xapp/__init__.py
python-xapp /usr/lib/python3.9/site-packages/xapp/__pycache__/
python-xapp /usr/lib/python3.9/site-packages/xapp/__pycache__/GSettingsWidgets.cpython-39.opt-1.pyc
python-xapp /usr/lib/python3.9/site-packages/xapp/__pycache__/GSettingsWidgets.cpython-39.pyc
python-xapp /usr/lib/python3.9/site-packages/xapp/__pycache__/SettingsWidgets.cpython-39.opt-1.pyc
python-xapp /usr/lib/python3.9/site-packages/xapp/__pycache__/SettingsWidgets.cpython-39.pyc
python-xapp /usr/lib/python3.9/site-packages/xapp/__pycache__/__init__.cpython-39.opt-1.pyc
python-xapp /usr/lib/python3.9/site-packages/xapp/__pycache__/__init__.cpython-39.pyc
python-xapp /usr/lib/python3.9/site-packages/xapp/__pycache__/os.cpython-39.opt-1.pyc
python-xapp /usr/lib/python3.9/site-packages/xapp/__pycache__/os.cpython-39.pyc
python-xapp /usr/lib/python3.9/site-packages/xapp/os.py
```

However 
```
mike@mike-pc:~$ python
Python 3.9.0 (default, Oct  7 2020, 23:09:01) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi.repository
>>> gi.require_version("XApp", "1.0")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace XApp not available
>>> 
```
What`s wrong with it?

**Comment by eli-schwartz** [comment]
Well, given this is not "import xapp" but going through GObject, the package you want is https://www.archlinux.org/packages/community/x86_64/xapp/ which doesn't even need to be rebuilt for python 3.9 due to the fact that it is GObject. But it does need to be installed.

However, it does install an override:

```
The only purpose of this file is to ensure the XApp widget GType is registered
at the time of import.  Otherwise any user of XApp.GtkWindow would have to create
a dummy widget prior to using a GtkBuilder to parse a ui file containing an
XAppGtkWindow.
```

Which.. is anyway rebuilt for python 3.9.

**Comment by clefebvre** [comment]
Ah yes, it's the gir package, my bad.

```
clem@airtop ~ $ apt content gir1.2-xapp-1.0 
/.
/usr
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/gi
/usr/lib/python3/dist-packages/gi/overrides
/usr/lib/python3/dist-packages/gi/overrides/XApp.py
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/girepository-1.0
/usr/lib/x86_64-linux-gnu/girepository-1.0/XApp-1.0.typelib
/usr/share
/usr/share/doc
/usr/share/doc/gir1.2-xapp-1.0
/usr/share/doc/gir1.2-xapp-1.0/changelog.gz
/usr/share/doc/gir1.2-xapp-1.0/copyright
```

**Comment by eli-schwartz** [comment]
In commit a819d570ebdc5ab2e910d1db85efa9382d0d6dd0 a dependency on the XApp gir was added to this file, though it was needed for other files since 2a4267673d6225166e45ee776e0411cdc894e442 long before.

On 2020-10-26 the new version of mintmenu with this file was packaged in the AUR, still without the needed packaging dependency, though it had been broken in preferences.ui since the 2020-03-17 version of the AUR package.

Because the AUR maintainer of mintmenu did not handle dependencies, possibly ever.

**Comment by leigh123linux** [comment]
> In commit [a819d57](https://github.com/linuxmint/mintmenu/commit/a819d570ebdc5ab2e910d1db85efa9382d0d6dd0) a 
> **Because the AUR maintainer of mintmenu did not handle dependencies, possibly ever**.

No surprise there.

**Comment by MikePooh** [comment]
`yaourt -Sy xapp` solved my problem. Thanks everyone.

**Comment by eli-schwartz** [comment]
Admittedly the README for this repository doesn't exactly go to great lengths to document anything.

@MikePooh Leave a comment on the AUR package, please.
